Watching for file changes with StatReloader
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2025 - 00:42:35
Django version 4.2, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

RDF 파일 로드 중: data/rdf/wellness.n-triples (형식: nt)
RDF 그래프 로드 완료: 37948 트리플
[DEBUG] 쿼리 실행: 
        SELECT ?p ?o WHERE {
            <http://www.wellness.ai/resource/02-016> ?p ?o .
            FILTER(?p != <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>)
            FILTER(?p != <http://www.wellness.ai/resource>)
        }
        
[DEBUG] 라벨 정보: pred_label=rdf-schema#label, obj_label=임신28주, is_uri=False
[DEBUG] 라벨 정보: pred_label=rdf-schema#label, obj_label=임신28주, is_uri=False
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=알코올, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=카페인, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=인스턴트식품, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=율무, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=생강, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=패스트푸드, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=팥, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=알로에, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=초콜릿, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=복어, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=녹두, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=파인애플, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=청량음료, is_uri=True
[DEBUG] 라벨 정보: pred_label=기피식품, obj_label=회, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=항간질제, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=음주, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=여성호르몬제, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=스트렙토마이신, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=여드름치료제, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=레이저, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=혈당강하제, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=탈리도마이드, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=테트라사이클린, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=슬리밍제품, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=영양제, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=보톡스, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=치아미백, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=이소트레티노인, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=흡연, is_uri=True
[DEBUG] 라벨 정보: pred_label=금지하다, obj_label=필러, is_uri=True
[DEBUG] 라벨 정보: pred_label=검사종류, obj_label=소변검사, is_uri=True
[DEBUG] 라벨 정보: pred_label=검사종류, obj_label=초음파검사, is_uri=True
[DEBUG] 라벨 정보: pred_label=검사종류, obj_label=복부초음파검사, is_uri=True
[DEBUG] 라벨 정보: pred_label=검사종류, obj_label=제대혈검사, is_uri=True
[DEBUG] 라벨 정보: pred_label=검사종류, obj_label=빈혈검사, is_uri=True
[DEBUG] 라벨 정보: pred_label=검사종류, obj_label=혈액검사, is_uri=True
[DEBUG] 라벨 정보: pred_label=검사종류, obj_label=입체초음파검사, is_uri=True
[DEBUG] 라벨 정보: pred_label=검사종류, obj_label=임신성당뇨검사, is_uri=True
[DEBUG] 라벨 정보: pred_label=받아야하는접종, obj_label=독감예방접종, is_uri=True
[DEBUG] 라벨 정보: pred_label=받아야하는접종, obj_label=백일해백신접종, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=고구마, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=시금치, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=칼슘제, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=굴, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=미역, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=감자, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=망고, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=브로콜리, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=계란, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=닭가슴살, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=사과, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=붉은살코기, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=돼지고기, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=간류, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=소고기, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=완두콩, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=저지방우유, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=오렌지, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=부추, is_uri=True
[DEBUG] 라벨 정보: pred_label=권장식품, obj_label=양배추, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=냉방기기, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=파마, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=살균표백제, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=자전거, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=섬유유연제, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=화장품, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=아로마오일, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=윗몸일으키기, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=에어로빅, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=조깅, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=화장, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=포화지방, is_uri=True
[DEBUG] 라벨 정보: pred_label=규제하다, obj_label=세정제, is_uri=True
[DEBUG] 라벨 정보: pred_label=관련질병, obj_label=포상기태, is_uri=True
[DEBUG] 라벨 정보: pred_label=관련질병, obj_label=임신중독증, is_uri=True
[DEBUG] 라벨 정보: pred_label=관련질병, obj_label=자간, is_uri=True
[DEBUG] 라벨 정보: pred_label=관련질병, obj_label=피부소양증, is_uri=True
[DEBUG] 라벨 정보: pred_label=관련질병, obj_label=임신우울증, is_uri=True
[DEBUG] 라벨 정보: pred_label=관련질병, obj_label=자궁경관무력증, is_uri=True
[DEBUG] 라벨 정보: pred_label=관련질병, obj_label=전치태반, is_uri=True
[DEBUG] 라벨 정보: pred_label=관련질병, obj_label=임신성포진, is_uri=True
[DEBUG] 라벨 정보: pred_label=관련복지제도, obj_label=태아보험, is_uri=True
[DEBUG] 라벨 정보: pred_label=관련복지제도, obj_label=임신출산진료비지원사업, is_uri=True
[DEBUG] 라벨 정보: pred_label=관련복지제도, obj_label=고운맘카드, is_uri=True
[DEBUG] 라벨 정보: pred_label=상태, obj_label=정맥류, is_uri=True
[DEBUG] 라벨 정보: pred_label=상태, obj_label=가슴 두근거림, is_uri=True
[DEBUG] 라벨 정보: pred_label=신체변화, obj_label=위가 쓰림, is_uri=False
[01/Mar/2025 00:42:39] "POST /v1/rag/rdf-analysis/ HTTP/1.1" 200 35788
/Users/yoobmooyeol/project/Florence_project/config/settings.py changed, reloading.
[DEBUG] 라벨 정보: pred_label=신체변화, obj_label=가려움, is_uri=False
[DEBUG] 라벨 정보: pred_label=신체변화, obj_label=피로를 쉽게 느낌, is_uri=False
[DEBUG] 라벨 정보: pred_label=신체변화, obj_label=팔다리가 부음, is_uri=False
[DEBUG] 라벨 정보: pred_label=신체변화, obj_label=임신선이 확실하게 나타남, is_uri=False
[DEBUG] 라벨 정보: pred_label=신체변화, obj_label=다리 저림, is_uri=False
[DEBUG] 라벨 정보: pred_label=신체변화, obj_label=에스트로겐 분비, is_uri=False
[DEBUG] 라벨 정보: pred_label=신체변화, obj_label=유방에서 초유가 만들어짐, is_uri=False
[DEBUG] 라벨 정보: pred_label=신체변화, obj_label=피부 트러블, is_uri=False
[DEBUG] 라벨 정보: pred_label=태아발달, obj_label=뇌가 커짐, is_uri=False
[DEBUG] 라벨 정보: pred_label=태아발달, obj_label=뇌 조직이 발달, is_uri=False
[DEBUG] 라벨 정보: pred_label=태아발달, obj_label=시각 거의 완성, is_uri=False
[DEBUG] 라벨 정보: pred_label=태아발달, obj_label=청각 거의 완성, is_uri=False
[DEBUG] 라벨 정보: pred_label=태아발달, obj_label=규칙적인 생활 리듬을 가짐, is_uri=False
[DEBUG] 라벨 정보: pred_label=태아발달, obj_label=망막세포의 성숙, is_uri=False
[DEBUG] 라벨 정보: pred_label=태아발달, obj_label=눈을 깜박임, is_uri=False
[DEBUG] 라벨 정보: pred_label=태아발달, obj_label=규칙적인 수면, is_uri=False
[DEBUG] 라벨 정보: pred_label=태아발달, obj_label=풍성한 머리숱, is_uri=False
[DEBUG] 라벨 정보: pred_label=태아발달, obj_label=피부 아래 지방층 축적, is_uri=False
[DEBUG] 라벨 정보: pred_label=태아신장, obj_label=35~39cm, is_uri=False
[DEBUG] 라벨 정보: pred_label=태아체중, obj_label=800~1200g, is_uri=False
[DEBUG] 라벨 정보: pred_label=해로운음식, obj_label=수은 함량이 많은 생선, is_uri=False
[DEBUG] 라벨 정보: pred_label=해로운음식, obj_label=기름에 볶은 음식, is_uri=False
[DEBUG] 라벨 정보: pred_label=해로운음식, obj_label=덜 익힌 고기, is_uri=False
[DEBUG] 라벨 정보: pred_label=해로운음식, obj_label=MSG가 첨가된 음식, is_uri=False
[DEBUG] 라벨 정보: pred_label=해로운음식, obj_label=덜익힌고기, is_uri=True
[DEBUG] 라벨 정보: pred_label=생활수칙, obj_label=태아보호를 위해 복대를 착용토록 함, is_uri=False
[DEBUG] 라벨 정보: pred_label=생활수칙, obj_label=피부가 건조하지 않도록 가습기를 가동하고 미지근한 물로 목욕함, is_uri=False
[DEBUG] 라벨 정보: pred_label=생활수칙, obj_label=무리한 움직임을 피하고 틈틈이 휴식을 취함, is_uri=False
[DEBUG] 라벨 정보: pred_label=생활수칙, obj_label=치질예방을 위해 하루 8~10잔 정도 물을 마시고 섬유질을 많이 섭취, is_uri=False
[DEBUG] 라벨 정보: pred_label=생활수칙, obj_label=종아리 마사지와 가벼운 아침산책, 임산부용 스타킹 착용 등을 생활화함, is_uri=False
[DEBUG] 라벨 정보: pred_label=생활수칙, obj_label=섬유질 음식을 섭취하고 오래 서있거나 않아 있지 말 것, is_uri=False
[DEBUG] 라벨 정보: pred_label=주의사항, obj_label=사우나 목욕은 하지 않도록 함, is_uri=False
[DEBUG] 라벨 정보: pred_label=주의사항, obj_label=철분과 칼슘은 충분히 섭취하고 동물성 지방은 가급적 피함, is_uri=False
[DEBUG] 라벨 정보: pred_label=주의사항, obj_label=규칙적인 생활을 하도록 함, is_uri=False
[DEBUG] 라벨 정보: pred_label=임신개월, obj_label=임신7개월, is_uri=True
[DEBUG] 라벨 정보: pred_label=좋은음식, obj_label=비타민B5 함유 음식, is_uri=False
[DEBUG] 최종 관계 수: 125
Watching for file changes with StatReloader
/Users/yoobmooyeol/project/Florence_project/config/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2025 - 00:57:01
Django version 4.2, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yoobmooyeol/project/Florence_project/config/urls.py", line 25, in <module>
    path("v1/sanitization/", include("sanitization.urls")),  # 산모 대상 LLM 서비스 앱
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/urls.py", line 3, in <module>
    from . import views
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/views.py", line 14, in <module>
    from .utils import MaternalHealthLLMService
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/utils.py", line 478
    """
       ^
SyntaxError: f-string expression part cannot include a backslash
/Users/yoobmooyeol/project/Florence_project/sanitization/admin.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yoobmooyeol/project/Florence_project/config/urls.py", line 25, in <module>
    path("v1/sanitization/", include("sanitization.urls")),  # 산모 대상 LLM 서비스 앱
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/urls.py", line 3, in <module>
    from . import views
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/views.py", line 14, in <module>
    from .utils import MaternalHealthLLMService
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/utils.py", line 478
    """
       ^
SyntaxError: f-string expression part cannot include a backslash
/Users/yoobmooyeol/project/Florence_project/sanitization/apps.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yoobmooyeol/project/Florence_project/config/urls.py", line 25, in <module>
    path("v1/sanitization/", include("sanitization.urls")),  # 산모 대상 LLM 서비스 앱
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/urls.py", line 3, in <module>
    from . import views
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/views.py", line 14, in <module>
    from .utils import MaternalHealthLLMService
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/utils.py", line 478
    """
       ^
SyntaxError: f-string expression part cannot include a backslash
/Users/yoobmooyeol/project/Florence_project/sanitization/utils.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/management/commands/runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yoobmooyeol/project/Florence_project/config/urls.py", line 25, in <module>
    path("v1/sanitization/", include("sanitization.urls")),  # 산모 대상 LLM 서비스 앱
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/urls.py", line 3, in <module>
    from . import views
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/views.py", line 14, in <module>
    from .utils import MaternalHealthLLMService
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/utils.py", line 478
    """
       ^
SyntaxError: f-string expression part cannot include a backslash
/Users/yoobmooyeol/project/Florence_project/sanitization/utils.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
/Users/yoobmooyeol/project/Florence_project/sanitization/utils.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2025 - 00:59:33
Django version 4.2, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/Users/yoobmooyeol/project/Florence_project/sanitization/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2025 - 00:59:35
Django version 4.2, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/Users/yoobmooyeol/project/Florence_project/sanitization/apps.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2025 - 01:04:35
Django version 4.2, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
/Users/yoobmooyeol/project/Florence_project/sanitization/urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 01, 2025 - 01:04:41
Django version 4.2, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.

Watching for file changes with StatReloader
[01/Mar/2025 01:10:09] "GET /v1/rag/rdf-query/ HTTP/1.1" 200 12792
[01/Mar/2025 01:10:09] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[01/Mar/2025 01:10:09] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[01/Mar/2025 01:10:09] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[01/Mar/2025 01:10:09] "GET /static/rest_framework/js/jquery-3.7.1.min.js HTTP/1.1" 304 0
[01/Mar/2025 01:10:09] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[01/Mar/2025 01:10:09] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[01/Mar/2025 01:10:09] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[01/Mar/2025 01:10:09] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[01/Mar/2025 01:10:09] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[01/Mar/2025 01:10:09] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[01/Mar/2025 01:10:09] "GET /static/rest_framework/js/load-ajax-form.js HTTP/1.1" 304 0
[01/Mar/2025 01:10:09] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Internal Server Error: /v1/sanitization/api/llm/
Traceback (most recent call last):
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
sqlite3.OperationalError: no such table: sanitization_usersession

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/sanitization/views.py", line 70, in post
    user_session, created = UserSession.objects.get_or_create(
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 916, in get_or_create
    return self.get(**kwargs), False
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/Users/yoobmooyeol/project/Florence_project/.venv/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
django.db.utils.OperationalError: no such table: sanitization_usersession
[01/Mar/2025 01:12:16] "POST /v1/sanitization/api/llm/ HTTP/1.1" 500 166657
